apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tembo-metrics.fullname" . }}
  labels:
    {{- include "tembo-metrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tembo-metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tembo-metrics.selectorLabels" . | nindent 8 }}
      {{- if .Values.prometheus.scrape }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.prometheus.path | quote }}
        prometheus.io/port: {{ .Values.prometheus.port | quote }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "tembo-metrics.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/bin/tembo-metrics"]
          args:
            - "--log-level"
            - "{{ .Values.config.logLevel }}"
            - "--region"
            - "{{ .Values.config.region }}"
            - "--server-host"
            - "{{ .Values.config.serverHost }}"
            - "--server-port"
            - "{{ .Values.config.serverPort }}"
          ports:
            - name: http
              containerPort: {{ .Values.config.serverPort }}
              protocol: TCP
          {{- if .Values.probes.liveness }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.readiness }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
